-- MySQL Script generated by MySQL Workbench
-- ter 29 jan 2019 14:47:00 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema expd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `doca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doca` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cod_doca` VARCHAR(45) NOT NULL,
  `status` INT(11) NOT NULL,
  `qnt_vagas` INT(11) NOT NULL,
  `tipo` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `groups` (
  `id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

INSERT INTO `groups` (`id`, `name`, `description`) VALUES
     (1,'admin','Administrator'),
     (2,'usuario','General User');


-- -----------------------------------------------------
-- Table `login_attempts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `login_attempts` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ip_address` VARCHAR(45) NOT NULL,
  `login` VARCHAR(100) NOT NULL,
  `time` INT(11) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `palete`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `palete` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cod_palete` VARCHAR(45) NOT NULL,
  `status` INT(11) NOT NULL,
  `qnt_vagas` INT(11) NOT NULL,
  `rota` VARCHAR(45) NOT NULL,
  `ativo` INT(11),  
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedido` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cod_pedido` VARCHAR(45) NOT NULL,
  `horario_entrada` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ocorrencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ocorrencia` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `horario_ocorrencia` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `tipo_ocorrencia` INT(11) NOT NULL,
  `palete_id` INT(11) NULL DEFAULT NULL,
  `pedido_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pedido_id_idx` (`pedido_id` ASC),
  INDEX `fk_palete_id_idx` (`palete_id` ASC),
  CONSTRAINT `fk_palete_id`
    FOREIGN KEY (`palete_id`)
    REFERENCES `palete` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_id`
    FOREIGN KEY (`pedido_id`)
    REFERENCES `pedido` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `palete_has_doca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `palete_has_doca` (
  `palete_id` INT(11) NOT NULL,
  `doca_id` INT(11) NOT NULL,
  PRIMARY KEY (`palete_id`, `doca_id`),
  INDEX `fk_palete_has_doca_doca1_idx` (`doca_id` ASC),
  INDEX `fk_palete_has_doca_palete1_idx` (`palete_id` ASC),
  CONSTRAINT `fk_palete_has_doca_doca1`
    FOREIGN KEY (`doca_id`)
    REFERENCES `doca` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_palete_has_doca_palete1`
    FOREIGN KEY (`palete_id`)
    REFERENCES `palete` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `palete_has_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `palete_has_pedido` (
  `palete_id` INT(11) NOT NULL,
  `pedido_id` INT(11) NOT NULL,
  PRIMARY KEY (`palete_id`, `pedido_id`),
  INDEX `fk_palete_has_pedido_pedido1_idx` (`pedido_id` ASC),
  INDEX `fk_palete_has_pedido_palete1_idx` (`palete_id` ASC),
  CONSTRAINT `fk_palete_has_pedido_palete1`
    FOREIGN KEY (`palete_id`)
    REFERENCES `palete` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_palete_has_pedido_pedido1`
    FOREIGN KEY (`pedido_id`)
    REFERENCES `pedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ip_address` VARCHAR(45) NOT NULL,
  `username` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(254) NOT NULL,
  `activation_selector` VARCHAR(255) NULL DEFAULT NULL,
  `activation_code` VARCHAR(255) NULL DEFAULT NULL,
  `forgotten_password_selector` VARCHAR(255) NULL DEFAULT NULL,
  `forgotten_password_code` VARCHAR(255) NULL DEFAULT NULL,
  `forgotten_password_time` INT(11) UNSIGNED NULL DEFAULT NULL,
  `remember_selector` VARCHAR(255) NULL DEFAULT NULL,
  `remember_code` VARCHAR(255) NULL DEFAULT NULL,
  `created_on` INT(11) UNSIGNED NOT NULL,
  `last_login` INT(11) UNSIGNED NULL DEFAULT NULL,
  `active` TINYINT(1) UNSIGNED NULL DEFAULT NULL,
  `first_name` VARCHAR(50) NULL DEFAULT NULL,
  `last_name` VARCHAR(50) NULL DEFAULT NULL,
  `company` VARCHAR(100) NULL DEFAULT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `uc_activation_selector` (`activation_selector` ASC),
  UNIQUE INDEX `uc_forgotten_password_selector` (`forgotten_password_selector` ASC),
  UNIQUE INDEX `uc_remember_selector` (`remember_selector` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

INSERT INTO `users` (`id`, `ip_address`, `username`, `password`, `email`, `activation_code`, `forgotten_password_code`, `created_on`, `last_login`, `active`, `first_name`, `last_name`, `company`, `phone`) VALUES
     ('1','127.0.0.1','admin','$2y$10$b5TvGkq7nhCdb5kutU0wyebAsgyRvZAnIUcxDAP3mgqXMwktPbBRm','admin@admin.com','',NULL,'1268889823','1268889823','1', 'Admin','ADM','ADMIN','0');

-- -----------------------------------------------------
-- Table `users_groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users_groups` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) UNSIGNED NOT NULL,
  `group_id` MEDIUMINT(8) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uc_users_groups` (`user_id` ASC, `group_id` ASC),
  INDEX `fk_users_groups_users1_idx` (`user_id` ASC),
  INDEX `fk_users_groups_groups1_idx` (`group_id` ASC),
  CONSTRAINT `fk_users_groups_groups1`
    FOREIGN KEY (`group_id`)
    REFERENCES `groups` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_groups_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

INSERT INTO `users_groups` (`id`, `user_id`, `group_id`) VALUES
     (1,1,1),
     (2,1,2);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
